version: "3.8"

services:
  express-app:
    build: .
    container_name: todo_list_server
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    # 如果你的代码里有连接重试机制，可以加上这个
    environment:
      - NODE_ENV=production
